import type { StyleConfig, ColorSchemeConfig, FontConfig, LayoutConfig } from "./types"

export const STYLE_TEMPLATES: Record<string, StyleConfig> = {
  modern: {
    name: "Modern",
    description: "Clean, contemporary design with subtle animations",
    preview: "🎨 Modern & Clean",
    bg: "bg-gradient-to-br from-slate-50 to-blue-50",
    primary: "from-blue-600 to-indigo-600",
    secondary: "from-slate-100 to-slate-200",
    accent: "text-blue-600",
    text: "text-slate-900",
    hover: "hover:from-blue-700 hover:to-indigo-700",
    cardStyle: "rounded-2xl shadow-xl",
    buttonStyle: "rounded-xl",
    sectionBg: "bg-white",
  },
  luxury: {
    name: "Luxury",
    description: "Premium gold and black luxury design",
    preview: "👑 Luxury & Premium",
    bg: "bg-gradient-to-br from-yellow-50 to-amber-100",
    primary: "from-yellow-500 to-amber-400",
    secondary: "from-yellow-100 to-amber-100",
    accent: "text-yellow-700",
    text: "text-gray-900",
    hover: "hover:from-yellow-700 hover:to-amber-700",
    cardStyle: "rounded-lg shadow-2xl border-2 border-yellow-500",
    buttonStyle: "rounded-full",
    sectionBg: "bg-gradient-to-br from-yellow-50 to-amber-100",
  },
  bold: {
    name: "Bold",
    description: "Vibrant colors and strong visual impact",
    preview: "🔥 Bold & Vibrant",
    bg: "bg-gradient-to-br from-orange-50 to-red-50",
    primary: "from-orange-600 to-red-600",
    secondary: "from-orange-100 to-red-100",
    accent: "text-orange-600",
    text: "text-gray-900",
    hover: "hover:from-orange-700 hover:to-red-700",
    cardStyle: "rounded-xl shadow-lg",
    buttonStyle: "rounded-lg",
    sectionBg: "bg-white",
  },
  classic: {
    name: "Classic",
    description: "Traditional, elegant design with serif fonts",
    preview: "📜 Classic & Elegant",
    bg: "bg-gradient-to-br from-stone-50 to-gray-100",
    primary: "from-stone-800 to-gray-900",
    secondary: "from-stone-100 to-gray-200",
    accent: "text-stone-800",
    text: "text-stone-900",
    hover: "hover:from-stone-900 hover:to-black",
    cardStyle: "rounded-lg shadow-md border border-stone-300",
    buttonStyle: "rounded",
    sectionBg: "bg-stone-50",
  },
  playful: {
    name: "Playful",
    description: "Fun, rounded, and colorful design",
    preview: "🎈 Playful & Fun",
    bg: "bg-gradient-to-br from-pink-50 to-purple-100",
    primary: "from-pink-400 to-purple-400",
    secondary: "from-pink-100 to-purple-100",
    accent: "text-pink-600",
    text: "text-gray-900",
    hover: "hover:from-pink-600 hover:to-purple-600",
    cardStyle: "rounded-3xl shadow-lg",
    buttonStyle: "rounded-full",
    sectionBg: "bg-pink-50",
  },
  professional: {
    name: "Professional",
    description: "Corporate, business-focused design",
    preview: "🏢 Professional & Corporate",
    bg: "bg-gradient-to-br from-blue-50 to-slate-100",
    primary: "from-slate-700 to-blue-800",
    secondary: "from-slate-100 to-blue-100",
    accent: "text-slate-700",
    text: "text-slate-900",
    hover: "hover:from-slate-800 hover:to-blue-900",
    cardStyle: "rounded-lg shadow-md",
    buttonStyle: "rounded-md",
    sectionBg: "bg-white",
  },
  tech: {
    name: "Tech",
    description: "Futuristic, clean, and tech-inspired design",
    preview: "💻 Tech & Modern",
    bg: "bg-gradient-to-br from-cyan-50 to-teal-50",
    primary: "from-cyan-500 to-teal-500",
    secondary: "from-cyan-100 to-teal-100",
    accent: "text-cyan-600",
    text: "text-gray-900",
    hover: "hover:from-cyan-600 hover:to-teal-600",
    cardStyle: "rounded-xl shadow-lg border border-cyan-200",
    buttonStyle: "rounded-lg",
    sectionBg: "bg-cyan-50",
  },
  artistic: {
    name: "Artistic",
    description: "Creative, expressive, and visually rich design",
    preview: "🎨 Artistic & Creative",
    bg: "bg-gradient-to-br from-indigo-50 to-purple-50",
    primary: "from-indigo-500 to-purple-500",
    secondary: "from-indigo-100 to-purple-100",
    accent: "text-indigo-600",
    text: "text-gray-900",
    hover: "hover:from-indigo-600 hover:to-purple-600",
    cardStyle: "rounded-2xl shadow-xl",
    buttonStyle: "rounded-xl",
    sectionBg: "bg-indigo-50",
  },
  elegant: {
    name: "Elegant",
    description: "Sophisticated design with premium feel",
    preview: "✨ Elegant & Sophisticated",
    bg: "bg-gradient-to-br from-gray-50 to-stone-100",
    primary: "from-stone-800 to-gray-900",
    secondary: "from-stone-100 to-gray-200",
    accent: "text-stone-800",
    text: "text-stone-900",
    hover: "hover:from-stone-900 hover:to-black",
    cardStyle: "rounded-lg shadow-md",
    buttonStyle: "rounded",
    sectionBg: "bg-stone-50",
  },
  minimal: {
    name: "Minimal",
    description: "Simple, clean design focused on content",
    preview: "⚪ Minimal & Clean",
    bg: "bg-white",
    primary: "from-gray-900 to-black",
    secondary: "from-gray-50 to-gray-100",
    accent: "text-gray-900",
    text: "text-gray-900",
    hover: "hover:from-black hover:to-gray-800",
    cardStyle: "rounded-none shadow-none border border-gray-200",
    buttonStyle: "rounded-none",
    sectionBg: "bg-white",
  },
  creative: {
    name: "Creative",
    description: "Artistic design with unique visual elements",
    preview: "🎭 Creative & Artistic",
    bg: "bg-gradient-to-br from-purple-50 to-pink-50",
    primary: "from-purple-600 to-pink-600",
    secondary: "from-purple-100 to-pink-100",
    accent: "text-purple-600",
    text: "text-gray-900",
    hover: "hover:from-purple-700 hover:to-pink-700",
    cardStyle: "rounded-3xl shadow-2xl",
    buttonStyle: "rounded-full",
    sectionBg: "bg-purple-50",
  },
  corporate: {
    name: "Corporate",
    description: "Professional business-focused design",
    preview: "🏢 Corporate & Professional",
    bg: "bg-gradient-to-br from-blue-50 to-slate-100",
    primary: "from-slate-700 to-blue-800",
    secondary: "from-slate-100 to-blue-100",
    accent: "text-slate-700",
    text: "text-slate-900",
    hover: "hover:from-slate-800 hover:to-blue-900",
    cardStyle: "rounded-lg shadow-md",
    buttonStyle: "rounded-md",
    sectionBg: "bg-white",
  },
  neon: {
    name: "Neon",
    description: "Futuristic neon-inspired design",
    preview: "⚡ Neon & Futuristic",
    bg: "bg-gradient-to-br from-cyan-50 to-teal-50",
    primary: "from-cyan-500 to-teal-500",
    secondary: "from-cyan-100 to-teal-100",
    accent: "text-cyan-600",
    text: "text-gray-900",
    hover: "hover:from-cyan-600 hover:to-teal-600",
    cardStyle: "rounded-xl shadow-lg border-2 border-cyan-300 shadow-cyan-500/50",
    buttonStyle: "rounded-full",
    sectionBg: "bg-cyan-50",
  },
  vintage: {
    name: "Vintage",
    description: "Classic retro-inspired design",
    preview: "📻 Vintage & Retro",
    bg: "bg-gradient-to-br from-amber-50 to-orange-50",
    primary: "from-amber-700 to-orange-700",
    secondary: "from-amber-100 to-orange-100",
    accent: "text-amber-800",
    text: "text-gray-900",
    hover: "hover:from-amber-800 hover:to-orange-800",
    cardStyle: "rounded-md shadow-lg border-2 border-amber-800",
    buttonStyle: "rounded-md",
    sectionBg: "bg-amber-50",
  },
  glassmorphism: {
    name: "Glass",
    description: "Modern glassmorphism design",
    preview: "🔮 Glass & Modern",
    bg: "bg-gradient-to-br from-indigo-50 to-purple-50",
    primary: "from-indigo-500 to-purple-500",
    secondary: "from-indigo-100 to-purple-100",
    accent: "text-indigo-600",
    text: "text-gray-900",
    hover: "hover:from-indigo-600 hover:to-purple-600",
    cardStyle: "bg-white/30 backdrop-blur-lg rounded-2xl shadow-lg border border-white/20",
    buttonStyle: "rounded-full",
    sectionBg: "bg-transparent",
  },
  nature: {
    name: "Nature",
    description: "Earth-inspired natural design",
    preview: "🌿 Nature & Organic",
    bg: "bg-gradient-to-br from-green-50 to-emerald-50",
    primary: "from-green-600 to-emerald-600",
    secondary: "from-green-100 to-emerald-100",
    accent: "text-green-700",
    text: "text-gray-900",
    hover: "hover:from-green-700 hover:to-emerald-700",
    cardStyle: "rounded-2xl shadow-lg",
    buttonStyle: "rounded-full",
    sectionBg: "bg-green-50",
  },
}

export const COLOR_SCHEMES: Record<string, ColorSchemeConfig> = {
  blue: {
    name: "Ocean Blue",
    primary: "from-blue-600 to-cyan-600",
    secondary: "from-blue-100 to-cyan-100",
    accent: "text-blue-600",
    bg: "bg-gradient-to-br from-blue-50 to-cyan-50",
    text: "text-slate-900",
    hover: "hover:from-blue-700 hover:to-cyan-700",
  },
  purple: {
    name: "Royal Purple",
    primary: "from-purple-600 to-violet-600",
    secondary: "from-purple-100 to-violet-100",
    accent: "text-purple-600",
    bg: "bg-gradient-to-br from-purple-50 to-violet-50",
    text: "text-slate-900",
    hover: "hover:from-purple-700 hover:to-violet-700",
  },
  green: {
    name: "Nature Green",
    primary: "from-green-600 to-emerald-600",
    secondary: "from-green-100 to-emerald-100",
    accent: "text-green-600",
    bg: "bg-gradient-to-br from-green-50 to-emerald-50",
    text: "text-slate-900",
    hover: "hover:from-green-700 hover:to-emerald-700",
  },
  orange: {
    name: "Sunset Orange",
    primary: "from-orange-600 to-amber-600",
    secondary: "from-orange-100 to-amber-100",
    accent: "text-orange-600",
    bg: "bg-gradient-to-br from-orange-50 to-amber-50",
    text: "text-slate-900",
    hover: "hover:from-orange-700 hover:to-amber-700",
  },
  red: {
    name: "Passion Red",
    primary: "from-red-600 to-rose-600",
    secondary: "from-red-100 to-rose-100",
    accent: "text-red-600",
    bg: "bg-gradient-to-br from-red-50 to-rose-50",
    text: "text-slate-900",
    hover: "hover:from-red-700 hover:to-rose-700",
  },
  dark: {
    name: "Dark Mode",
    primary: "from-gray-800 to-slate-900",
    secondary: "from-gray-700 to-slate-800",
    accent: "text-gray-300",
    bg: "bg-gradient-to-br from-gray-900 to-slate-900",
    text: "text-gray-100",
    hover: "hover:from-gray-900 hover:to-black",
  },
  gold: {
    name: "Luxury Gold",
    primary: "from-yellow-500 to-amber-400",
    secondary: "from-yellow-100 to-amber-100",
    accent: "text-yellow-700",
    bg: "bg-gradient-to-br from-yellow-50 to-amber-50",
    text: "text-gray-900",
    hover: "hover:from-yellow-700 hover:to-amber-700",
  },
  teal: {
    name: "Ocean Teal",
    primary: "from-teal-500 to-cyan-400",
    secondary: "from-teal-100 to-cyan-100",
    accent: "text-teal-600",
    bg: "bg-gradient-to-br from-teal-50 to-cyan-50",
    text: "text-slate-900",
    hover: "hover:from-teal-700 hover:to-cyan-700",
  },
  rose: {
    name: "Rose Gold",
    primary: "from-rose-400 to-pink-400",
    secondary: "from-rose-100 to-pink-100",
    accent: "text-rose-600",
    bg: "bg-gradient-to-br from-rose-50 to-pink-50",
    text: "text-slate-900",
    hover: "hover:from-rose-600 hover:to-pink-600",
  },
  slate: {
    name: "Modern Slate",
    primary: "from-slate-600 to-gray-600",
    secondary: "from-slate-100 to-gray-100",
    accent: "text-slate-600",
    bg: "bg-gradient-to-br from-slate-50 to-gray-50",
    text: "text-slate-900",
    hover: "hover:from-slate-700 hover:to-gray-700",
  },
  rainbow: {
    name: "Rainbow",
    primary: "from-pink-500 via-purple-500 to-indigo-500",
    secondary: "from-pink-100 via-purple-100 to-indigo-100",
    accent: "text-purple-600",
    bg: "bg-gradient-to-br from-pink-50 via-purple-50 to-indigo-50",
    text: "text-slate-900",
    hover: "hover:from-pink-600 hover:via-purple-600 hover:to-indigo-600",
  },
}

export const FONT_STYLES: Record<string, FontConfig> = {
  modern: {
    name: "Modern Sans",
    description: "Clean, contemporary typography",
    headingFont: "font-sans",
    bodyFont: "font-sans",
    className: "font-sans",
  },
  classic: {
    name: "Classic Serif",
    description: "Traditional, elegant typography",
    headingFont: "font-serif",
    bodyFont: "font-serif",
    className: "font-serif",
  },
  playful: {
    name: "Playful Rounded",
    description: "Friendly, approachable typography",
    headingFont: "font-sans",
    bodyFont: "font-sans",
    className: "font-sans tracking-wide",
  },
  professional: {
    name: "Professional",
    description: "Business-focused, readable typography",
    headingFont: "font-sans",
    bodyFont: "font-sans",
    className: "font-sans font-medium",
  },
  luxury: {
    name: "Luxury Script",
    description: "Elegant script-inspired typography",
    headingFont: "font-serif",
    bodyFont: "font-sans",
    className: "font-serif tracking-wide",
  },
  tech: {
    name: "Tech Mono",
    description: "Modern monospace for tech businesses",
    headingFont: "font-mono",
    bodyFont: "font-sans",
    className: "font-mono tracking-tight",
  },
  artistic: {
    name: "Artistic Display",
    description: "Creative display typography",
    headingFont: "font-sans",
    bodyFont: "font-sans",
    className: "font-sans tracking-wider font-light",
  },
  bold: {
    name: "Bold Impact",
    description: "Strong, impactful typography",
    headingFont: "font-sans",
    bodyFont: "font-sans",
    className: "font-sans font-bold tracking-tight",
  },
}

export const LAYOUT_STYLES: Record<string, LayoutConfig> = {
  centered: {
    name: "Centered",
    description: "Content centered with max width",
    className: "max-w-4xl mx-auto",
  },
  "full-width": {
    name: "Full Width",
    description: "Content spans full width of screen",
    className: "max-w-full mx-auto",
  },
  "card-based": {
    name: "Card Based",
    description: "Content organized in card layouts",
    className: "max-w-6xl mx-auto",
  },
  magazine: {
    name: "Magazine",
    description: "Editorial-style layout with columns",
    className: "max-w-5xl mx-auto",
  },
  minimal: {
    name: "Minimal",
    description: "Clean, spacious minimal layout",
    className: "max-w-3xl mx-auto",
  },
  wide: {
    name: "Wide Screen",
    description: "Optimized for wide screens",
    className: "max-w-7xl mx-auto",
  },
}
