import type { SavedBusiness } from "./types"

export const sampleBusinesses: SavedBusiness[] = [
  {
    id: "sample-restaurant-1",
    userId: "sample-user-1",
    plan: "premium",
    slug: "fresh-bites-restaurant",
    fullName: "Adebayo Johnson",
    businessName: "Fresh Bites Restaurant",
    businessDescription:
      "We serve delicious local and continental dishes made with fresh, locally-sourced ingredients in a warm, welcoming atmosphere.",
    productDescription:
      "Our menu features authentic Nigerian cuisine alongside international favorites, prepared by expert chefs with passion for culinary excellence.",
    location: "Victoria Island, Lagos",
    fullAddress: "123 Ahmadu Bello Way, Victoria Island, Lagos, Nigeria",
    businessPlan:
      "Our mission is to become Lagos' premier dining destination by combining traditional Nigerian flavors with modern culinary techniques, while supporting local farmers and suppliers.",
    logoUrl: "",
    ownerPictureUrl: "",
    siteStyle: "elegant",
    colorScheme: "orange",
    fontStyle: "classic",
    layoutStyle: "centered",
    contactOption: "both",
    contactNumber: "+234 801 234 5678",
    interestedInPremium: true,
    language: "en",
    coordinates: { lat: 6.4281, lng: 3.4219 },
    showMap: true,
    whatsappSettings: {
      welcomeMessage: "Hi! Welcome to Fresh Bites Restaurant. How can we help you today?",
      businessHours: true,
      autoReply: true,
      chatPosition: "bottom-right",
    },
    enableAI: true,
    enableAnalytics: true,
    enableSEO: true,
    enableLeadCapture: true,
    enableBooking: true,
    enableReviews: true,
    socialLinks: {
      facebook: "https://facebook.com/freshbitesrestaurant",
      instagram: "@freshbiteslagos",
    },
    businessHours: {
      monday: "10:00 AM - 10:00 PM",
      tuesday: "10:00 AM - 10:00 PM",
      wednesday: "10:00 AM - 10:00 PM",
      thursday: "10:00 AM - 10:00 PM",
      friday: "10:00 AM - 11:00 PM",
      saturday: "9:00 AM - 11:00 PM",
      sunday: "12:00 PM - 9:00 PM",
    },
    keywords: ["restaurant", "Nigerian cuisine", "Lagos dining", "fresh food"],
    aiGeneratedReviews: [
      {
        name: "Chioma Okafor",
        rating: 5,
        comment:
          "The food here is absolutely amazing! Fresh ingredients and authentic flavors. Will definitely be back!",
        location: "Lagos",
        verified: true,
      },
      {
        name: "Ibrahim Musa",
        rating: 5,
        comment: "Best dining experience I've had in Lagos. The service was exceptional and the atmosphere perfect.",
        location: "Abuja",
        verified: true,
      },
      {
        name: "Funmi Adeyemi",
        rating: 4,
        comment: "Outstanding cuisine and friendly staff. This place never disappoints!",
        location: "Lagos",
        verified: false,
      },
    ],
    analytics: {
      views: 1247,
      clicks: 89,
      leads: 23,
      whatsappClicks: 45,
      phoneClicks: 31,
      mapClicks: 13,
      lastVisit: new Date().toISOString(),
      dailyStats: {
        "2024-01-15": { views: 45, clicks: 3, leads: 1 },
        "2024-01-14": { views: 52, clicks: 4, leads: 2 },
        "2024-01-13": { views: 38, clicks: 2, leads: 0 },
        "2024-01-12": { views: 61, clicks: 5, leads: 3 },
        "2024-01-11": { views: 43, clicks: 3, leads: 1 },
        "2024-01-10": { views: 55, clicks: 4, leads: 2 },
        "2024-01-09": { views: 49, clicks: 3, leads: 1 },
      },
      topPages: [
        { page: "Landing Page", views: 856 },
        { page: "Contact Section", views: 234 },
        { page: "Services", views: 157 },
      ],
      deviceStats: {
        mobile: 68,
        desktop: 25,
        tablet: 7,
      },
      locationStats: {
        Nigeria: 78,
        Ghana: 12,
        Kenya: 6,
        "South Africa": 4,
      },
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "sample-tech-2",
    userId: "sample-user-2",
    plan: "basic",
    slug: "tech-solutions-hub",
    fullName: "Emeka Nwankwo",
    businessName: "Tech Solutions Hub",
    businessDescription:
      "We deliver cutting-edge technology solutions that empower businesses to thrive in the digital age through innovation and expertise.",
    productDescription:
      "Comprehensive tech services including software development, digital transformation, cloud solutions, and IT consulting tailored to your business needs.",
    location: "Lekki, Lagos",
    fullAddress: "45 Admiralty Way, Lekki Phase 1, Lagos, Nigeria",
    businessPlan:
      "We aim to be the leading technology partner for Nigerian businesses seeking digital excellence, focusing on delivering scalable, secure, and innovative solutions.",
    logoUrl: "",
    ownerPictureUrl: "",
    siteStyle: "modern",
    colorScheme: "blue",
    fontStyle: "tech",
    layoutStyle: "card-based",
    contactOption: "both",
    contactNumber: "+234 802 345 6789",
    interestedInPremium: true,
    language: "en",
    coordinates: { lat: 6.4474, lng: 3.4539 },
    showMap: true,
    whatsappSettings: {
      welcomeMessage: "Hello! Welcome to Tech Solutions Hub. How can we assist with your technology needs?",
      businessHours: true,
      autoReply: true,
      chatPosition: "bottom-right",
    },
    enableAI: true,
    enableAnalytics: true,
    enableSEO: true,
    enableLeadCapture: true,
    enableBooking: true,
    enableReviews: true,
    socialLinks: {
      linkedin: "https://linkedin.com/company/techsolutionshub",
      twitter: "@techsolutionshub",
    },
    businessHours: {
      monday: "8:00 AM - 6:00 PM",
      tuesday: "8:00 AM - 6:00 PM",
      wednesday: "8:00 AM - 6:00 PM",
      thursday: "8:00 AM - 6:00 PM",
      friday: "8:00 AM - 6:00 PM",
      saturday: "9:00 AM - 2:00 PM",
    },
    keywords: ["technology", "software development", "IT consulting", "digital transformation"],
    aiGeneratedReviews: [
      {
        name: "Aisha Abdullahi",
        rating: 5,
        comment:
          "Professional service and cutting-edge solutions. They transformed our business operations completely.",
        location: "Abuja",
        verified: true,
      },
      {
        name: "Tunde Ogundimu",
        rating: 5,
        comment: "Excellent technical expertise and customer support. Highly recommend for any tech needs.",
        location: "Lagos",
        verified: true,
      },
    ],
    analytics: {
      views: 892,
      clicks: 67,
      leads: 18,
      whatsappClicks: 32,
      phoneClicks: 25,
      mapClicks: 10,
      lastVisit: new Date().toISOString(),
      dailyStats: {
        "2024-01-15": { views: 32, clicks: 2, leads: 1 },
        "2024-01-14": { views: 41, clicks: 3, leads: 1 },
        "2024-01-13": { views: 28, clicks: 1, leads: 0 },
        "2024-01-12": { views: 45, clicks: 4, leads: 2 },
        "2024-01-11": { views: 38, clicks: 2, leads: 1 },
        "2024-01-10": { views: 42, clicks: 3, leads: 1 },
        "2024-01-09": { views: 35, clicks: 2, leads: 0 },
      },
      topPages: [
        { page: "Landing Page", views: 623 },
        { page: "Services", views: 189 },
        { page: "Contact", views: 80 },
      ],
      deviceStats: {
        mobile: 45,
        desktop: 48,
        tablet: 7,
      },
      locationStats: {
        Nigeria: 85,
        Ghana: 8,
        Kenya: 4,
        "South Africa": 3,
      },
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "sample-beauty-3",
    userId: "sample-user-3",
    plan: "premium",
    slug: "beauty-wellness-spa",
    fullName: "Blessing Okoro",
    businessName: "Beauty & Wellness Spa",
    businessDescription:
      "Your premier destination for beauty treatments, wellness services, and relaxation in a serene, professional environment.",
    productDescription:
      "We offer a full range of beauty services including facials, massages, hair treatments, nail care, and wellness therapies using premium products.",
    location: "Ikeja, Lagos",
    fullAddress: "78 Allen Avenue, Ikeja, Lagos, Nigeria",
    businessPlan:
      "To become Lagos' most trusted beauty and wellness destination by providing exceptional services that enhance our clients' natural beauty and well-being.",
    logoUrl: "",
    ownerPictureUrl: "",
    siteStyle: "luxury",
    colorScheme: "rose",
    fontStyle: "luxury",
    layoutStyle: "centered",
    contactOption: "whatsapp",
    contactNumber: "+234 803 456 7890",
    interestedInPremium: true,
    language: "en",
    coordinates: { lat: 6.6018, lng: 3.3515 },
    showMap: true,
    whatsappSettings: {
      welcomeMessage: "Welcome to Beauty & Wellness Spa! How can we pamper you today?",
      businessHours: true,
      autoReply: true,
      chatPosition: "bottom-right",
    },
    enableAI: true,
    enableAnalytics: true,
    enableSEO: true,
    enableLeadCapture: true,
    enableBooking: true,
    enableReviews: true,
    socialLinks: {
      instagram: "@beautywellnessspa",
      facebook: "https://facebook.com/beautywellnessspa",
    },
    businessHours: {
      monday: "9:00 AM - 7:00 PM",
      tuesday: "9:00 AM - 7:00 PM",
      wednesday: "9:00 AM - 7:00 PM",
      thursday: "9:00 AM - 7:00 PM",
      friday: "9:00 AM - 8:00 PM",
      saturday: "8:00 AM - 8:00 PM",
      sunday: "10:00 AM - 6:00 PM",
    },
    keywords: ["beauty spa", "wellness", "massage", "facial treatments", "Lagos"],
    aiGeneratedReviews: [
      {
        name: "Ngozi Eze",
        rating: 5,
        comment: "Amazing service! I left feeling absolutely beautiful and confident.",
        location: "Lagos",
        verified: true,
      },
      {
        name: "Kemi Adebisi",
        rating: 5,
        comment: "Professional staff and high-quality products. My skin has never looked better!",
        location: "Lagos",
        verified: true,
      },
    ],
    analytics: {
      views: 1456,
      clicks: 112,
      leads: 34,
      whatsappClicks: 78,
      phoneClicks: 0,
      mapClicks: 34,
      lastVisit: new Date().toISOString(),
      dailyStats: {
        "2024-01-15": { views: 58, clicks: 5, leads: 2 },
        "2024-01-14": { views: 62, clicks: 6, leads: 3 },
        "2024-01-13": { views: 45, clicks: 3, leads: 1 },
        "2024-01-12": { views: 71, clicks: 7, leads: 4 },
        "2024-01-11": { views: 53, clicks: 4, leads: 2 },
        "2024-01-10": { views: 67, clicks: 6, leads: 3 },
        "2024-01-09": { views: 59, clicks: 5, leads: 2 },
      },
      topPages: [
        { page: "Landing Page", views: 1012 },
        { page: "Services", views: 298 },
        { page: "Booking", views: 146 },
      ],
      deviceStats: {
        mobile: 82,
        desktop: 15,
        tablet: 3,
      },
      locationStats: {
        Nigeria: 92,
        Ghana: 5,
        Kenya: 2,
        "South Africa": 1,
      },
    },
    createdAt: new Date().toISOString(),
  },
]
